### ISSUE TITLE
Working on fedora

### ISSUE THREAD

**Issue by aishwar-yaaa** [FOSSersVAST/distros#7]
What to give for Based on: , since it is an independent OS?

**Comment by subins2000** [comment]
@abspython gave `Based On: Linux Kernel` for Debain entry : https://github.com/FOSSersVAST/distros/pull/2#discussion-diff-226413661R11

I think OS like Debian, Fedora etc. which are not based on an existing OS shouldn't have a **Based On** field. But to keep consistency with other entries, what to do :/

I'm confused on this.

cc @ravenbinds @KhadijaAMH

**Comment by subins2000** [comment]
#8 merged. Closing
